services:
  python:
    build:
      context: ./backend/python
    ports:
      - "8000:8000"
    volumes:
      - "./backend/python:/app"

  bun:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - "./backend:/app"
    environment:
      - ARTNET_IP=host.docker.internal
      - ARTNET_PORT=6454

  web:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
